# -*- encoding: utf8 -*-

MESSAGE_COUNT_REDIS_KEY_PREFIX = "MESSAGE_COUNT_"
MESSAGE_DAILY_COUNT_REDIS_KEY_PREFIX = "MESSAGE_DAILY_COUNT_"
LOGIN_VERIFY_CODE_SWITCH_CLOSED = "closed"
LOGIN_CODE_SEND_DAY_LIMIT = 15
LOGIN_CODE_SEND_TWO_HOUR_LIMIT = 5