# -*- coding: utf-8 -*-

PROJ_STATUS_INIT = 0
PROJ_STATUS_WORKING = 1
PROJ_STATUS_END = 2
PROJ_STATUS_EXCEPTION = 3

# 1-创建，2-更改，3-删除，4，状态变更'
PROJ_OP_TYPE_CREATE = 1
PROJ_OP_TYPE_UPDATE = 2
PROJ_OP_TYPE_DELETE = 3
PROJ_OP_TYPE_CHANGE_STATUS = 4

